### ISSUE TITLE
[BUG] -

### ISSUE THREAD

**Issue by blmhemu** [jitesoft/docker-step-ca#1]
docker-compose.yml 
step-ca:
        image: jitesoft/step-ca
        environment:
            CONFIGPATH: /home/step/.step/config/ca.json
            PWDPATH: /home/step/.step/secrets/password.txt
        volumes:
            - stepca:/home/step
            - /home/ubuntu/Docker/password.txt:/home/step/.step/secrets/password.txt
        ports:
            - 443:443
Error :
step-ca_1  | error opening ${CONFIGPATH}: open ${CONFIGPATH}: no such file or directory
But when using custom command, it says tty not available.

**Comment by Johannestegner** [comment]
Hi @blmhemu ! Thank you for the report, I made a mistake in the image "CMD" and will fix this right away!

**Comment by Johannestegner** [comment]
I have updated the image to run the (what was earlier in) the CMD clause in the Entrypoint script for now.  
It should solve the initial issue (as soon as the image is up on docker hub), while I will take a closer look at making it a bit neater when I have more time in a couple of hours!

_note: leaving the issue open to remind me to fix this in a better way!_

**Comment by Johannestegner** [comment]
0.14.6 Is up on docker hub now with latest entrypoint script.

**Comment by blmhemu** [comment]
Thanks for the quick fix. It is working as expected now.
I have encountered a weird problem (running this for my private ACME server along with step-cli) :
    * When i expose a port, i am not able to access it from outside the container (i.e localhost).
    * But when i use host network (--network host) then it works fine.

https://pastebin.com/nCP9WYvN : The script i use for running my ACME server.

**Comment by Johannestegner** [comment]
> Thanks for the quick fix. It is working as expected now.

Glad to hear! :)

> I have encountered a weird problem (running this for my private ACME server along with step-cli) :
> * When i expose a port, i am not able to access it from outside the container (i.e localhost).
> * But when i use host network (--network host) then it works fine.

That is odd, do you expose the correct port? Looking at your script, it should be `:8443`, so `-p 8443:8443`.  
In difference with the official image, I have decided to not (at the least at the moment) add network cap to allow non-root to bind to the lower -end ports, so could you try use say... 16443:16443 and see if that works? I _can_ add the cap if it is really wanted, but I personally prefer to bind to higher ports than to mess with the capabilities as I want my containers to use as little privilege as possible! :)

Let me know if 16443 works, in that case it is the caps, else I'll look further in to it! :)

**Comment by blmhemu** [comment]
> That is odd, do you expose the correct port? Looking at your script, it should be :8443, so -p 8443:8443.

Yeah i have expose the correct port. The above configuration was old one.

> so could you try use say... 16443:16443 and see if that works? 

Yup I have used the below configs /  commands :

Step-cli  (for configuartion)
`docker run -it --rm -v step_ca_vol:/home/step -v /home/ubuntu/Docker/password.txt:/home/step/password.txt jitesoft/step-cli /bin/sh -c "step ca init --name Pi --dns pi.in --address localhost:16443 --provisioner=pi@pi.in --password-file=/home/step/password.txt && step ca provisioner add acme --type ACME"`


Step-ca (for running actual server)
```
step-ca:
        image: jitesoft/step-ca
        environment:
            CONFIGPATH: /home/step/.step/config/ca.json
            PWDPATH: /home/step/password.txt
        volumes:
            - step_ca_vol:/home/step
            - /home/ubuntu/Docker/password.txt:/home/step/password.txt
        ports:
            - 16443:16443
volumes:
    step_ca_vol:
        external: true
```

There was no error running any of the above containers. Docker logs seem perfectly normal.

But when I do ` curl --insecure https://localhost:16443/acme/acme/directory` I get the following result.
curl: (35) OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to localhost:16443

I have also tried in a web browser from another computer over the same network and got `ERR_CONNECTION_REFUSED`

Before going into the error details, can you please verify that the above two commands are correct ? Especially `--dns pi.in --address localhost:16443`  part of 1st command.

**Comment by blmhemu** [comment]
I have tried various configs. Somehow using the below command seems to work. Please note the use of "0.0.0.0" for --address.

`docker run -it --rm -v step_ca_vol:/home/step -v /home/ubuntu/Docker/password.txt:/home/step/password.txt jitesoft/step-cli /bin/sh -c "step ca init --name Pi --dns pi.in --address 0.0.0.0:16443 --provisioner=pi@pi.in --password-file=/home/step/password.txt && step ca provisioner add acme --type ACME"`

Also when i try to change the port to 443 instead of 16443, it gives bind error `step-ca_1  | listen tcp 0.0.0.0:443: bind: permission denied` . I assume this is because of insufficient permissions inside the container (may be the network cap thing you mentioned in the earlier post ?) Since most services run behind a reverse proxy (traefik or nginx), would it not be good to use the standard 443 and 80 ports using network cap ?

**Comment by Johannestegner** [comment]
Aaah, yes, I usually just let it bind to address `:16443` (or `0.0.0.0:16443`) instead of using the ip, else it will only listen to localhost connections.
And yes, the 443 bind issue is due to the cap's inside the container.

I do agree that it would be quite nice to bind the ports inside the container to 80/443, but it does give the container permissions that you wouldn't usually prefer that a non-root user have. I guess that in this case, it does not really matter, not like the step container will start binding up ports and that it even would create any issues, but the easiest way is to bind the container port to a privileged port on the host, that is, 443:16443 (where the former is host and the latter the container).

**Comment by blmhemu** [comment]
Thanks for the all the help @Johannestegner . My docker compose is now up and running.
